[workspace]
resolver = "2"
members = [
    "lir-core",
    "lir-codegen",
    "lir-repl",
    "lir-cli",
    "lir-lair",
    "cert",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
